from normal.normalSudoku import NormalSudoku

def createSudoku():
    sudoku = NormalSudoku(9)
    sudoku.Set( 0, 0, 9, True)
    sudoku.Set( 0, 8, 6, True)
    sudoku.Set( 1, 3, 9, True)
    sudoku.Set( 1, 6, 5, True)    
    sudoku.Set( 1, 7, 2, True)
    sudoku.Set( 2, 0, 5, True)
    sudoku.Set( 2, 2, 7, True)
    sudoku.Set( 2, 4, 3, True)
    sudoku.Set( 2, 5, 6, True)
    sudoku.Set( 2, 7, 1, True)
    sudoku.Set( 3, 0, 2, True)
    sudoku.Set( 3, 2, 4, True)
    sudoku.Set( 4, 3, 6, True)
    sudoku.Set( 4, 5, 2, True)
    sudoku.Set( 5, 6, 7, True)
    sudoku.Set( 5, 8, 2, True)
    sudoku.Set( 6, 1, 2, True)
    sudoku.Set( 6, 3, 1, True)
    sudoku.Set( 6, 4, 7, True)
    sudoku.Set( 6, 6, 6, True)
    sudoku.Set( 6, 8, 4, True)
    sudoku.Set( 7, 1, 9, True)
    sudoku.Set( 7, 2, 1, True)
    sudoku.Set( 7, 5, 5, True)
    sudoku.Set( 8, 0, 3, True)
    sudoku.Set( 8, 8, 7, True)
    sudoku.DoChange() # set the changes
    return sudoku
